Repository collage-us/collage, pull requests merged in 2024-07, with the labels that each got.

#21 Revise return value of login backend
  collage/server/main.py
Labels: bug

#23 Add starter code for `data.sql` and `schema.sql`
  database/data.sql
  database/schema.sql
Labels: new-feature

#26 Refine recommendation algorithm; Add `users` table and `courses` table
  collage/server/main.py
  collage/server/recommend.py
  database/data.sql
  database/schema.sql
Labels: new-feature

#31 Revise `requirements.txt` for new Python dependencies; revise `README.md`; style changes
  README.md
  collage/server/auth.py
  collage/server/helper.py
  collage/server/main.py
  collage/server/recommend.py
  requirements.txt
Labels: documentation

#32 `DALL-E` image generator backend; New Columns in `courses` table
  collage/server/dalle.py
  collage/server/main.py
  collage/server/recommend.py
  database/schema.sql
  requirements.txt
Labels: new-feature

#33 Fix API URL error: add init.py for `server` directory
  collage/server/__init__.py
  collage/server/dalle.py
  collage/server/main.py
Labels: bug

#34 Add `deploy.yml` for CI/CD workflow
  .github/workflows/deploy.yml
Labels: new-feature

#35 Set up GitHub Actions for Frontend
  .github/workflows/deploy.yml
  .github/workflows/deploy_frontend.yml
  collage/frontend/CSS/Home.css
  collage/frontend/CSS/Navbar.css
  collage/frontend/CSS/Signup.css
  collage/frontend/Landing/Home-1.jsx
  collage/frontend/Landing/Home-2.jsx
  collage/frontend/Landing/Home-3.jsx
  collage/frontend/Landing/Home-4.jsx
  collage/frontend/Landing/Home.jsx
  collage/frontend/Login/Wrapper.jsx
  collage/frontend/Navbar.jsx
  collage/frontend/Signup/Signup-2.jsx
  collage/frontend/Signup/Signup-3.jsx
  collage/frontend/Signup/Wrapper.jsx
  package-lock.json
Labels: new-feature

#36 Revise `publish_dir` in GitHub Actions Flow
  .github/workflows/deploy_frontend.yml
Labels: bug

#37 Add pull request template for future PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#38 Add `/upload/resume/` endpoint; Add `parse_resume()` using `nltk` & `PyPDF2`; Add new Python dep
  collage/server/auth.py
  collage/server/helper.py
  collage/server/main.py
  requirements.txt
Labels: documentation, new-feature

#39 Add database query for updating user `keywords` generated by `parse_resume()`
  collage/server/main.py
  collage/server/nltk.py
Labels: enhancement

#40 Revise `README.md`; Add `docs` directory for documentation
  README.md
  docs/recomm.md
  images/catalog_demo.png
  images/login_demo.png
Labels: documentation

#41 Added Course Catalog frontend
  collage/frontend/Home/CourseBox.jsx
  collage/frontend/Home/Home.jsx
  collage/frontend/Home/ProfileBar.jsx
  collage/frontend/Landing/Landing-1.jsx
  collage/frontend/Landing/Landing-2.jsx
  collage/frontend/Landing/Landing-3.jsx
  collage/frontend/Landing/Landing-4.jsx
  collage/frontend/Landing/Landing.jsx
  collage/frontend/Navbar.jsx
  collage/frontend/registration.jsx
Labels: new-feature

#42 Set up Heroku CI/CD
  .github/workflows/deploy_frontend.yml
  Procfile
  runtime.txt
Labels: enhancement

#44 Add new Python dependencies to requirements.txt; add yarn.lock
  collage/frontend/Navbar.jsx
  collage/server/__init__.py
  collage/server/main.py
  package-lock.json
  requirements.txt
  wsgi.py
  yarn.lock
Labels: bug

#45 Reinstall package-lock.json
  package-lock.json
  yarn.lock
Labels: bug

#46 Specify `node` version in `package.json`; update `package-lock.json`
  package-lock.json
  package.json
Labels: bug

#47 Fix Procfile and configurations
  Procfile
Labels: bug

#48 Move database env variable to `.env`
  collage/config.py
  collage/model.py
Labels: enhancement

#49 Add code splitting to optimize size of bundle.js; remove big pics
  .gitignore
  bin/run_production.sh
  collage/frontend/Auth.jsx
  collage/frontend/Home/Home.jsx
  collage/frontend/Landing/Landing.jsx
  collage/frontend/Login/Wrapper.jsx
  collage/frontend/Search/Wrapper.jsx
  collage/frontend/Signup/Wrapper.jsx
  collage/frontend/images/background-3.png
  collage/frontend/images/green-logo.png
  collage/frontend/main.jsx
  collage/frontend/registration.jsx
  collage/static/js/bundle.js.LICENSE.txt
  collage/static/js/collage/frontend/images/background-3.png
  requirements.txt
Labels: bug

#50 Solve green-logo import error on `Heroku`
  collage/frontend/images/green-logo.png
Labels: bug

#51 Backend Functionality for Save Button; `save_courses` table; `find-cache-dir` package for JS
  .github/PULL_REQUEST_TEMPLATE.md
  bin/install.sh
  bin/run.sh
  bin/run_production.sh
  collage/server/main.py
  database/schema.sql
  package-lock.json
  package.json
Labels: new-feature

#53 Finish basic QA of Collage AI Agent; rename `nltk_utils.py`; update `package-lock.json`; update Python dep & PR template
  .github/PULL_REQUEST_TEMPLATE.md
  collage/server/agent.py
  collage/server/main.py
  collage/server/nltk_utils.py
  package-lock.json
  requirements.txt
Labels: documentation, enhancement, new-feature

#52 Imported lazy component
  collage/frontend/Auth.jsx
  collage/frontend/Home/Home.jsx
  collage/frontend/Landing/Landing.jsx
  collage/frontend/Login/Wrapper.jsx
  collage/frontend/Search/Wrapper.jsx
  collage/frontend/Signup/Wrapper.jsx
  collage/frontend/main.jsx
  collage/frontend/registration.jsx
Labels: bug

#55 AI Agent Prompt Optimization; add `--omit=dev`
  collage/server/agent.py
  package-lock.json
  package.json
Labels: bug, enhancement

#56 Omit nltk data downloading for Heroku
  collage/server/nltk_utils.py
Labels: bug

#57 Backend Functionality for the Individual Course Page
  collage/server/agent.py
  collage/server/course.py
  database/schema.sql
Labels: new-feature
